### ISSUE TITLE
Improper DVS Trunk PortGroup Implementation

### ISSUE THREAD

**Issue by silveraid** [gbolo/vSummary#2]
The _Get-VSDistributedPortGroup_ function of the PowerCLI collector does not handle the trunk port groups properly, neither do the API.

If a port group is configured as _Trunk_ the _vim.dvs.DistributedVirtualPortgroup._ _Config.DefaultPortConfig.Vlan.VlanId_ variable turns into an array as it could have more than one from-to vlan pairs.

_Please add support to the API to be able to handle this._

**Comment by gbolo** [comment]
Sorry, haven't ntoiced this open issue.

`Get-VSDistributedPortGroup` should support the following two vlan types:

```
# Single vlan
VmwareDistributedVirtualSwitchVlanIdSpec
# Trunk
VmwareDistributedVirtualSwitchTrunkVlanSpec
```

I tested creating a trunked portgroup like:

```
testtrunk: 1-4,100,200-202
```

After running the powershell collector and going through php api it ended up in the database like:

```
MariaDB [vsummary]> select name, vlan_type, vlan from view_portgroup WHERE name='testtrunk';
+-----------+-----------+-----------------------+
| name      | vlan_type | vlan                  |
+-----------+-----------+-----------------------+
| testtrunk | trunk     | 1 - 4, 100, 200 - 202 |
+-----------+-----------+-----------------------+
1 row in set (0.01 sec)
```

Is this not the expected behaviour?

**Comment by silveraid** [comment]
You are right, I missed the _vlan_trunk_to_string_ function in the API. I will make the Python script behave as the PowerCLI script does.

When I have VLANs _5-20,25-28,45,46,47_, PowerCLI sends over the following strings:

`"vlan_end":  "20 28 45 46 47", "vlan_start":  "5 25 45 46 47"`

**Comment by silveraid** [comment]
This issue has been fixed.
